# Generated by Django 3.1 on 2020-09-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='passward',
            field=models.CharField(max_length=10),
        ),
    ]
