# Generated by Django 3.1 on 2020-09-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200906_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='password',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
